steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/attendx', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/attendx']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'attendx-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/attendx'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '3080'

images:
  - 'gcr.io/$PROJECT_ID/attendx'
